resources:
  repositories:
  # The name used to reference this repository in the checkout step
  - repository: VuBashCalcRepo 
    type: github
    endpoint: VuGitHub
    name: mynameisvu/bashCalc
# The name used to reference this repository in the checkout step
  - repository: VuWindowsBatchRepo
    type: github
    endpoint: VuGitHub
    name: mynameisvu/winBatch

trigger:
- master

stages:

#First Stage on Ubuntu
- stage: UbuntuQAEnvCheck
  jobs:
  - job: InlineScripts

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: none
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
